const translationsArtwork = {
    en: {
        meta_title: "Artwork Gallery - Nuria Serrano | 3D Environment & Technical Artist",
        meta_desc: "Explore the technical art portfolio of Nuria Serrano, featuring 3D environment optimization, PBR channel packing, and shader breakdowns.",
        
        side_featured: "Featured",
        side_technical: "Technical",
        side_materials: "Materials",
        side_lighting: "Lighting",
        side_gallery: "Gallery",

        nav_home: "Home",
        nav_work: "Work",
        nav_artwork: "3D & Technical Art",
        nav_games: "Games & Sims",
        nav_about: "About me",
        nav_resume: "Resumé",
        nav_contact: "Contact",

        hero_eyebrow: "✦ TECHNICAL ART PORTFOLIO",
        hero_title_1: "3D Environment",
        hero_title_2: "Optimization",
        hero_subtitle: "Real-time rendering, technical pipeline optimization, and shader development for professional simulation and interactive experiences.",

        feat_tag: "Full Pipeline Project",
        feat_title: "ECOE 3D Simulator",
        feat_desc: "Complete technical direction for a clinical simulation platform. 5+ months developing modular PBR assets, implementing shader graph solutions, optimizing render pipeline, and compositing post-processing effects for real-time performance.",
        render_view: "Render View",
        tech_breakdown: "Technical Breakdown",
        spec_triangles: "Triangles",
        spec_drawcalls: "Draw Calls",
        spec_textures: "Atlased Textures",
        spec_lighting: "Lighting",
        spec_lighting_val: "Hybrid",

        stat_mat_variants: "Material Variants",
        stat_tex_maps: "Texture Maps",
        stat_pipeline: "Pipeline",
        stat_target_perf: "Target Performance",

        sub1_title: "Topology & Wireframe",
        sub1_desc: "Clean quad-based topology. Optimized edge flow for deformation, supporting modular assembly across scenes.",
        sub2_title: "Efficient UVs & Atlasing",
        sub2_desc: "Channel-packed RGBA maps. Consistent texel density (512px/m). Multiple materials sharing single atlas.",
        sub3_title: "Hybrid Lighting Approach",
        sub3_desc: "Baked GI + Light Probes + Real-time lights. Compositing passes for post-pro mood and ambient occlusion.",

        opt_tag: "Performance Metrics & Pipeline",
        opt_title: "Technical Optimization",
        opt_desc: "ECOE Simulator: From 2,000 draw calls to 200. Real-time profiling data from Unity Profiler.",
        opt_before: "Before Optimization (Raw Import)",
        opt_after: "After Optimization (Best Practices)",

        perf_comp_title: "Performance Comparison",
        table_setpass: "SetPass Calls",
        table_drawcalls: "Draw Calls",
        table_triangles: "Triangles",
        table_framerate: "Frame Rate",

        tech_opt_title: "Optimization Techniques",
        tech1_title: "Static Batching",
        tech1_desc: "Grouped meshes sharing materials. Allowed the GPU to render in combined batches rather than thousands of individual calls.",
        tech2_title: "Texture Atlasing",
        tech2_desc: "Combined multiple object textures into unified atlases, drastically dropping state changes and SetPass overhead (2.5k → 31).",
        tech3_title: "Mesh Collider Removal",
        tech3_desc: "Replaced overly complex mesh colliders with simplified primitive Box Colliders to minimize physics overhead.",
        tech4_title: "Baked Lighting",
        tech4_desc: "Pre-calculated illumination and utilized Light Probes for dynamic elements, eliminating real-time per-frame calculations.",

        target_specs_title: "Target Specifications",
        spec_fps: "FPS (Achieved)",
        spec_drawcalls_card: "Draw Calls",
        spec_triangles_card: "Triangles",
        spec_setpass_card: "SetPass Calls",

        mat_tag: "PBR & Texture Optimization",
        mat_title: "Channel Packing",
        mat_desc: "60% memory reduction using RGBA channel optimization. One atlas replaces 5 separate textures.",
        chan_r: "R Channel",
        chan_metallic: "Metallic",
        chan_g: "G Channel",
        chan_ao: "Ambient Occlusion",
        chan_b: "B Channel",
        chan_roughness: "Roughness",
        chan_a: "A Channel",
        chan_mask: "Mask / Detail",
        chan_rgba: "RGBA Combined",
        chan_final: "Final ORM Atlas",

        benefits_title: "Channel Packing Benefits",
        ben1_title: "60% Texture Memory Reduction",
        ben1_desc: "Combines Metallic (R), Ambient Occlusion (G), Roughness (B) in single RGBA texture. Bandwidth savings verified with Unity Profiler.",
        ben2_title: "Single Texture Sample",
        ben2_desc: "GPU reads one file instead of three. Reduces fragment shader instructions. Improves cache locality.",
        ben3_title: "Scalable Asset Pipeline",
        ben3_desc: "New objects integrate into existing atlas without increasing draw calls or SetPass calls. Future-proof architecture.",

        shader_tag: "Technical Art & Shaders",
        shader_main_title: "Pastel 2D Sticker FX",
        shader_desc: 'How to convert a 3D model into a 2D illustration? I developed a workflow combining Grease Pencil and Compositing to achieve this "hand-drawn" look.',
        step1: "Clean Outlines with Grease Pencil",
        step2: "Compositing: Dilate/Erode Sticker Border",
        step3: "Anime Style Sparkles & Highlights",
        btn_tutorial: "Full Tutorial",
        slider_raw: "Raw Render",
        slider_final: "Final Shader",

        light_tag: "ECOE Simulator",
        light_title: "Lighting & Optimization",
        light_desc: "Baked GI strategy for clinical environment. 20 Point/Spot lights + Reflection Probes. Real-time free.",
        light_vid_title: "Baked Global Illumination",
        light_vid_sub: "Lightmaps 512px + Light Probes Grid",
        light_conf_title: "Lighting Configuration",
        lc1_title: "Baked GI",
        lc1_desc: "Lightmaps 512px. Indirect bounces precalculated. Zero real-time cost.",
        lc2_title: "20 Point/Spot Lights",
        lc2_desc: "Simulate fluorescents (5500K). Baked only. Dynamic objects use Light Probes.",
        lc3_title: "Reflection Probes",
        lc3_desc: "Cubemap captures. Enable realistic reflections on materials without real-time cost.",

        spec_lm_label: "Lightmap Resolution",
        spec_lm_val: "512 pixels",
        spec_lp_label: "Light Probe Spacing",
        spec_lp_val: "1.5 meters",

        asset_tag: "Asset Pipeline",
        asset_title: "Modular Assets",
        asset_sub: "Game-ready 3D models with optimization focus",
        tab_gameready: "Game Ready",
        tab_highpoly: "High Poly",
        pill_opt: "Optimized",
        asset1_name: "Modular Town Wall",
        asset1_sub: "Environment Set · 2026",
        card_tri: "Triangles",
        card_texel: "Texel D.",
        pill_hero: "Hero Prop",
        asset2_name: "Ancient Magic Chest",
        asset2_sub: "Hero Prop · Animated",
        card_maps: "Maps",
        pill_highpoly: "High Poly",
        asset3_name: "Detailed Sculpt Pass",
        asset3_sub: "ZBrush Raw Asset",
        card_subs: "Subdivisions",

        tool_tag: "Educational Tool",
        tool_title: "Rendering Settings",
        tool_desc: "Interactive toggles to visualize optimization impact. Inspect how each technique affects frame rate and quality.",
        set_light: "Baked Lighting",
        set_light_sub: "GPU-free · +0 draw calls",
        set_post: "Post-Processing",
        set_post_sub: "AO · Bloom · Color Grading",
        opt_high: "High Resolution",
        opt_med: "Medium Resolution",
        opt_low: "Low / Disabled",
        set_shadow: "Shadow Quality",
        set_shadow_sub: "Quality/Performance tradeoff",
        set_part: "Particle Effects",
        set_part_sub: "Dust & atmospheric elements",
        set_ref: "Real-time Reflections",
        set_ref_sub: "SSR disabled · Uses probes",
        perf_est: "Estimated Performance",
        tool_note: "This is an educational visualization. The simulator achieves 120+ FPS with all quality settings enabled. Toggle options to understand the performance cost of each optimization technique.",

        stack_tag: "Tools & Technologies",
        stack_title: "Technical Stack",
        stack_desc: "Production software and engine configuration used for ECOE Simulator development.",
        stack_box1_title: "3D Modeling",
        s1_i1: "Blender",
        s1_i1_sub: "(advanced)",
        s1_i2: "3ds Max (rigging)",
        s1_i3: "SketchUp (blockout)",
        stack_box2_title: "Rendering & Shaders",
        s2_i1: "Unity URP",
        s2_i2: "Shader Graph",
        s2_i3: "HLSL basics",
        stack_box3_title: "Optimization",
        s3_i1: "Unity Profiler",
        s3_i2: "Frame Debugger basics",
        s3_i3: "Static Batching",
        s3_i4: "Occlusion Culling",
        stack_box4_title: "Texturing",
        s4_i1: "Substance Painter",
        s4_i2: "Blender Compositor",
        s4_i3: "Channel Packing (ORM)",
        stack_box5_title: "Pipeline",
        s5_i1: "UV Unwrap (Advanced)",
        s5_i2: "Texture Baking",
        s5_i3: "Normal Maps",
        stack_box6_title: "Version Control",
        s6_i1: "Git / GitHub",
        s6_i2: "GitHub Desktop",
        s6_i3: "Agile/Scrum",
        s6_i4: "Jira (tracking)",

        gallery_title: "Technical Gallery",
        filter_all: "All Works",
        filter_artwork: "3D Artwork",
        filter_concept: "Concepts",
        filter_sculpt: "Sculpting",
        filter_materials: "Materials",

        cta_title: "Let's build something optimized",
        cta_sub: "Technical art for real-time performance",
        cta_btn_contact: "Contact",
        cta_btn_cv: "CV",

        footer_tagline: "3D Technical Artist | Real-time Optimization",
        footer_explore: "Explore",
        footer_artwork: "Technical Art",
        footer_games: "Games & Sims",
        footer_touch: "Get in Touch",
        footer_contact_form: "Contact Form",
        footer_email: "Email Me",
        footer_note: "Available for freelance & collaboration.",
        footer_rights: "All Rights Reserved.",
        footer_credit: "Built with technical precision & Blender"
    },
    es: {
        meta_title: "Galería de Arte - Nuria Serrano | Artista de Entornos 3D y Technical Artist",
        meta_desc: "Explora el portfolio de arte técnico de Nuria Serrano, incluyendo optimización de entornos 3D, channel packing PBR y análisis de shaders.",
        
        side_featured: "Destacado",
        side_technical: "Técnico",
        side_materials: "Materiales",
        side_lighting: "Iluminación",
        side_gallery: "Galería",

        nav_home: "Inicio",
        nav_work: "Trabajos",
        nav_artwork: "Arte 3D y Técnico",
        nav_games: "Juegos y Simulación",
        nav_about: "Sobre mí",
        nav_resume: "Currículum",
        nav_contact: "Contacto",

        hero_eyebrow: "✦ PORTFOLIO DE ARTE TÉCNICO",
        hero_title_1: "Optimización de",
        hero_title_2: "Entornos 3D",
        hero_subtitle: "Renderizado en tiempo real, optimización de pipelines técnicos y desarrollo de shaders para simulación profesional y experiencias interactivas.",

        feat_tag: "Proyecto de Pipeline Completo",
        feat_title: "Simulador 3D ECOE",
        feat_desc: "Dirección técnica completa para una plataforma de simulación clínica. Más de 5 meses desarrollando assets PBR modulares, implementando soluciones en Shader Graph, optimizando el pipeline de renderizado y componiendo efectos de post-procesado para rendimiento en tiempo real.",
        render_view: "Vista de Render",
        tech_breakdown: "Desglose Técnico",
        spec_triangles: "Triángulos",
        spec_drawcalls: "Draw Calls",
        spec_textures: "Texturas Atlaseadas",
        spec_lighting: "Iluminación",
        spec_lighting_val: "Híbrida",

        stat_mat_variants: "Variantes de Materiales",
        stat_tex_maps: "Mapas de Texturas",
        stat_pipeline: "Pipeline",
        stat_target_perf: "Rendimiento Objetivo",

        sub1_title: "Topología y Wireframe",
        sub1_desc: "Topología limpia basada en quads. Flujo de aristas optimizado para deformación, admitiendo ensamblaje modular entre escenas.",
        sub2_title: "UVs Eficientes y Atlasing",
        sub2_desc: "Mapas RGBA empaquetados por canales. Densidad de séxeles consistente (512px/m). Viales múltiples compartiendo un solo atlas.",
        sub3_title: "Enfoque de Iluminación Híbrida",
        sub3_desc: "GI Bakeada + Light Probes + Luces en tiempo real. Pases de composición para ambiente y oclusión ambiental.",

        opt_tag: "Métricas de Rendimiento y Pipeline",
        opt_title: "Optimización Técnica",
        opt_desc: "Simulador ECOE: De 2,000 draw calls a 200. Datos de profiling en tiempo real desde Unity Profiler.",
        opt_before: "Antes de Optimizar (Importación Bruta)",
        opt_after: "Después de Optimizar (Buenas Prácticas)",

        perf_comp_title: "Comparativa de Rendimiento",
        table_setpass: "SetPass Calls",
        table_drawcalls: "Draw Calls",
        table_triangles: "Triángulos",
        table_framerate: "Tasa de Fotogramas",

        tech_opt_title: "Técnicas de Optimización",
        tech1_title: "Static Batching",
        tech1_desc: "Mallas agrupadas compartiendo materiales. Permitió a la GPU renderizar en lotes combinados en lugar de miles de llamadas individuales.",
        tech2_title: "Texture Atlasing",
        tech2_desc: "Combinación de múltiples texturas de objetos en atlas unificados, reduciendo drásticamente los cambios de estado y sobrecarga de SetPass (2.5k → 31).",
        tech3_title: "Eliminación de Mesh Colliders",
        tech3_desc: "Sustitución de colliders de malla excesivamente complejos por Box Colliders primitivos simplificados para minimizar sobrecarga física.",
        tech4_title: "Iluminación Bakeada",
        tech4_desc: "Iluminación precalculada y uso de Light Probes para elementos dinámicos, eliminando cálculos por fotograma en tiempo real.",

        target_specs_title: "Especificaciones Objetivo",
        spec_fps: "FPS (Alcanzados)",
        spec_drawcalls_card: "Draw Calls",
        spec_triangles_card: "Triángulos",
        spec_setpass_card: "SetPass Calls",

        mat_tag: "Optimización PBR y Texturas",
        mat_title: "Channel Packing",
        mat_desc: "Reducción de memoria del 60% usando optimización de canales RGBA. Un solo atlas reemplaza 5 texturas separadas.",
        chan_r: "Canal R",
        chan_metallic: "Metálico",
        chan_g: "Canal G",
        chan_ao: "Oclusión Ambiental",
        chan_b: "Canal B",
        chan_roughness: "Rugosidad",
        chan_a: "Canal A",
        chan_mask: "Máscara / Detalle",
        chan_rgba: "RGBA Combinado",
        chan_final: "Atlas ORM Final",

        benefits_title: "Beneficios de Channel Packing",
        ben1_title: "60% Menos Memoria de Texturas",
        ben1_desc: "Combina Metálico (R), Oclusión Ambiental (G) y Rugosidad (B) en una sola textura RGBA. Ahorro de ancho de banda verificado con Unity Profiler.",
        ben2_title: "Muestreo de Textura Único",
        ben2_desc: "La GPU lee un solo archivo en lugar de tres. Reduce las instrucciones del fragment shader y mejora la localidad de caché.",
        ben3_title: "Pipeline de Assets Escalable",
        ben3_desc: "Nuevos objetos se integran en el atlas existente sin aumentar draw calls o SetPass calls. Arquitectura preparada para el futuro.",

        shader_tag: "Arte Técnico y Shaders",
        shader_main_title: "FX de Sticker Pastel 2D",
        shader_desc: '¿Cómo convertir un modelo 3D en una ilustración 2D? Desarrollé un flujo de trabajo combinando Grease Pencil y Compositing para lograr este aspecto "dibujado a mano".',
        step1: "Contornos limpios con Grease Pencil",
        step2: "Compositing: Dilatar/Erosionar borde de pegatina",
        step3: "Brillos y destellos de estilo anime",
        btn_tutorial: "Tutorial Completo",
        slider_raw: "Render Bruto",
        slider_final: "Shader Final",

        light_tag: "Simulador ECOE",
        light_title: "Iluminación y Optimización",
        light_desc: "Estrategia de GI Bakeada para entorno clínico. 20 luces Point/Spot + Reflection Probes. Coste cero en tiempo real.",
        light_vid_title: "Iluminación Global Bakeada",
        light_vid_sub: "Lightmaps 512px + Rejilla de Light Probes",
        light_conf_title: "Configuración de Iluminación",
        lc1_title: "GI Bakeada",
        lc1_desc: "Lightmaps de 512px. Rebotes indirectos precalculados. Coste cero en tiempo real.",
        lc2_title: "20 Luces Point/Spot",
        lc2_desc: "Simulan fluorescentes (5500K). Bakeadas exclusivamente. Los objetos dinámicos usan Light Probes.",
        lc3_title: "Reflection Probes",
        lc3_desc: "Capturas de cubemap. Permiten reflejos realistas en materiales sin coste en tiempo real.",

        spec_lm_label: "Resolución de Lightmap",
        spec_lm_val: "512 píxeles",
        spec_lp_label: "Separación de Light Probes",
        spec_lp_val: "1.5 metros",

        asset_tag: "Pipeline de Assets",
        asset_title: "Assets Modulares",
        asset_sub: "Modelos 3D listos para videojuegos con enfoque en optimización",
        tab_gameready: "Game Ready",
        tab_highpoly: "High Poly",
        pill_opt: "Optimizado",
        asset1_name: "Muro de Ciudad Modular",
        asset1_sub: "Set de Entorno · 2026",
        card_tri: "Triángulos",
        card_texel: "Densidad Téxel",
        pill_hero: "Prop Principal",
        asset2_name: "Cofre Mágico Antiguo",
        asset2_sub: "Prop Principal · Animado",
        card_maps: "Mapas",
        pill_highpoly: "High Poly",
        asset3_name: "Paso de Esculpido Detallado",
        asset3_sub: "Asset Bruto de ZBrush",
        card_subs: "Subdivisiones",

        tool_tag: "Herramienta Educativa",
        tool_title: "Ajustes de Renderizado",
        tool_desc: "Controles interactivos para visualizar el impacto de la optimización. Inspecciona cómo cada técnica afecta al rendimiento y la calidad.",
        set_light: "Iluminación Bakeada",
        set_light_sub: "Sin uso de GPU · +0 draw calls",
        set_post: "Post-Procesado",
        set_post_sub: "AO · Bloom · Color Grading",
        opt_high: "Alta Resolución",
        opt_med: "Resolución Media",
        opt_low: "Baja / Desactivado",
        set_shadow: "Calidad de Sombras",
        set_shadow_sub: "Compromiso calidad/rendimiento",
        set_part: "Efectos de Partículas",
        set_part_sub: "Polvo y elementos atmosféricos",
        set_ref: "Reflejos en Tiempo Real",
        set_ref_sub: "SSR desactivado · Usa probes",
        perf_est: "Rendimiento Estimado",
        tool_note: "Esta es una visualización educativa. El simulador alcanza más de 120 FPS con todas las opciones de calidad activadas. Cambia las opciones para comprender el coste de rendimiento de cada técnica.",

        stack_tag: "Herramientas y Tecnologías",
        stack_title: "Stack Técnico",
        stack_desc: "Software de producción y configuración de motor utilizada para el desarrollo del Simulador ECOE.",
        stack_box1_title: "Modelado 3D",
        s1_i1: "Blender",
        s1_i1_sub: "(avanzado)",
        s1_i2: "3ds Max (rigging)",
        s1_i3: "SketchUp (blockout)",
        stack_box2_title: "Renderizado y Shaders",
        s2_i1: "Unity URP",
        s2_i2: "Shader Graph",
        s2_i3: "Bases de HLSL",
        stack_box3_title: "Optimización",
        s3_i1: "Unity Profiler",
        s3_i2: "Conceptos de Frame Debugger",
        s3_i3: "Static Batching",
        s3_i4: "Occlusion Culling",
        stack_box4_title: "Texturizado",
        s4_i1: "Substance Painter",
        s4_i2: "Blender Compositor",
        s4_i3: "Channel Packing (ORM)",
        stack_box5_title: "Pipeline",
        s5_i1: "Despliegue UV (Avanzado)",
        s5_i2: "Baking de Texturas",
        s5_i3: "Mapas de Normales",
        stack_box6_title: "Control de Versiones",
        s6_i1: "Git / GitHub",
        s6_i2: "GitHub Desktop",
        s6_i3: "Metodología Ágil/Scrum",
        s6_i4: "Jira (seguimiento)",

        gallery_title: "Galería Técnica",
        filter_all: "Todos",
        filter_artwork: "Arte 3D",
        filter_concept: "Conceptos",
        filter_sculpt: "Esculpido",
        filter_materials: "Materiales",

        cta_title: "Construyamos algo optimizado",
        cta_sub: "Arte técnico para rendimiento en tiempo real",
        cta_btn_contact: "Contacto",
        cta_btn_cv: "CV",

        footer_tagline: "Artista Técnico 3D | Optimización en Tiempo Real",
        footer_explore: "Explorar",
        footer_artwork: "Arte Técnico",
        footer_games: "Juegos y Simulación",
        footer_touch: "Ponte en Contacto",
        footer_contact_form: "Formulario de Contacto",
        footer_email: "Envíame un Email",
        footer_note: "Disponible para freelance y colaboración.",
        footer_rights: "Todos los derechos reservados.",
        footer_credit: "Hecho con precisión técnica y Blender"
    }
};

function changeLanguageArtwork(lang) {
    document.querySelectorAll("[data-i18n]").forEach(element => {
        const key = element.getAttribute("data-i18n");
        if (translationsArtwork[lang] && translationsArtwork[lang][key]) {
            element.textContent = translationsArtwork[lang][key];
        }
    });

    if (translationsArtwork[lang]["meta_title"]) {
        document.title = translationsArtwork[lang]["meta_title"];
    }

    localStorage.setItem("preferred_lang", lang);
    const btn = document.getElementById("lang-toggle");
    if (btn) {
        btn.textContent = lang === "es" ? "EN" : "ES";
    }
}

document.addEventListener("DOMContentLoaded", () => {
    const savedLang = localStorage.getItem("preferred_lang") || "en";
    if (savedLang === "es") {
        changeLanguageArtwork("es");
    }

    const toggleBtn = document.getElementById("lang-toggle");
    if (toggleBtn) {
        toggleBtn.addEventListener("click", () => {
            const currentLang = localStorage.getItem("preferred_lang") || "en";
            const newLang = currentLang === "en" ? "es" : "en";
            changeLanguageArtwork(newLang);
        });
    }
});